- name: ping hosts
  hosts: all
  tasks:
    - name: ping hosts
      ansible.windows.win_ping:

    - name: run python D:\get_vm.py
      ansible.windows.win_command:
        cmd: '"D:\get_vm.py"'
        chdir: D:\
      register: result
    
    - name: show result
      debug:
        msg: "{{ result }}"